spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.109:8848

server:
  port: 10101

dubbo:
  application:
    name: provider
  registry:
    address: nacos://192.168.0.109:8848
  scan:
    basePackages: com.scl.dubbo.service

management:
  endpoints:
    web:
      exposure:
        include: "*"